// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vbawolmkjkfmzjjzcvhn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZiYXdvbG1ramtmbXpqanpjdmhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQyMTgzNDQsImV4cCI6MjA0OTc5NDM0NH0.MtUo5xM_jGnMDgg_bMm8eQ38_77ZsOAh3S8GKdOfyYg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);